version: "3.9"

services:
  yolov8-sahi-gradio:
    build: .
    volumes:
      - ./models:/app/models # Монтирование папки models в контейнер
    ports:
      - "7860:7860"
    command: python app.py
